package com.myspace.ccd_project;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class FraudData implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Automated")
	private java.lang.Boolean automated;
	@org.kie.api.definition.type.Label("Customer Status")
	private java.lang.String customerStatus;
	@org.kie.api.definition.type.Label("RiskRating")
	private java.lang.Integer disputeRiskRating;
	@org.kie.api.definition.type.Label("FraudAmount")
	private java.lang.Float totalFraudAmount;

	public FraudData() {
	}

	public java.lang.Boolean getAutomated() {
		return this.automated;
	}

	public void setAutomated(java.lang.Boolean automated) {
		this.automated = automated;
	}

	public java.lang.String getCustomerStatus() {
		return this.customerStatus;
	}

	public void setCustomerStatus(java.lang.String customerStatus) {
		this.customerStatus = customerStatus;
	}

	public java.lang.Integer getDisputeRiskRating() {
		return this.disputeRiskRating;
	}

	public void setDisputeRiskRating(java.lang.Integer disputeRiskRating) {
		this.disputeRiskRating = disputeRiskRating;
	}

	public java.lang.Float getTotalFraudAmount() {
		return this.totalFraudAmount;
	}

	public void setTotalFraudAmount(java.lang.Float totalFraudAmount) {
		this.totalFraudAmount = totalFraudAmount;
	}

	public FraudData(java.lang.Boolean automated,
			java.lang.String customerStatus,
			java.lang.Integer disputeRiskRating,
			java.lang.Float totalFraudAmount) {
		this.automated = automated;
		this.customerStatus = customerStatus;
		this.disputeRiskRating = disputeRiskRating;
		this.totalFraudAmount = totalFraudAmount;
	}

}
